name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      dependencies: ${{ steps.set-matrix.outputs.dependencies }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
            echo "Finding package.json files..."
            # Find all package.json files, excluding those in node_modules directories
            PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*')

            echo "Found package.json files:"
            echo "$PACKAGES"

            MATRIX_JSON="{\"include\":$(echo "$PACKAGES" | jq -R -s -c 'split("\n")[:-1] | map({"package": (. | rtrimstr("/package.json"))})')}"
            echo "matrix = $MATRIX_JSON"
            echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

            PACKAGE_NAMES=()

            # Iterate over each package.json file
            for PACKAGE in $PACKAGES; do
                # Extract the name field from the package.json file
                if [ -f "$PACKAGE" ]; then
                    NAME=$(jq -r '.name' "$PACKAGE" | tr -d '\n' | tr -d '\r')
                    if [ "$NAME" != "null" ]; then
                         PACKAGE_NAME=$(jq -r '.name' "$PACKAGE")
                         PACKAGE_NAMES+=("$PACKAGE_NAME")
                    fi
                fi
            done

            # Convert the array of package names to a JSON array
            PACKAGE_NAMES_JSON=$(printf '%s\n' "${PACKAGE_NAMES[@]}" | jq -R -s -c 'split("\n")[:-1]')
            echo "dependencies = $PACKAGE_NAMES_JSON"
            
            # New code to iterate over the package.json files and extract dependencies
            DEPENDENCIES_MAP="{"
            for PACKAGE in $PACKAGES; do
                if [ -f "$PACKAGE" ]; then
                    # Filter and collect dependencies that are in the PACKAGE_NAMES_JSON
                    FILTERED_DEPS=$(jq -r --argjson packageNames "$PACKAGE_NAMES_JSON" \
                        '.dependencies | to_entries | map(select(.key as $k | $packageNames | index($k))) | map("\"" + .key + "\"") | join(",")' "$PACKAGE")
                    
                    # Format the output to match the required structure
                    if [[ $FILTERED_DEPS != "" ]]; then
                        DEPENDENCIES_MAP+="\"$(echo $PACKAGE | sed 's|/package.json||')\":[$FILTERED_DEPS],"
                    else
                        DEPENDENCIES_MAP+="\"$(echo $PACKAGE | sed 's|/package.json||')\":[],"
                    fi
                fi
            done
            # Remove the trailing comma to ensure valid JSON format
            DEPENDENCIES_MAP=${DEPENDENCIES_MAP%,}
            DEPENDENCIES_MAP+="}"

            echo "dependencies map = $DEPENDENCIES_MAP"
            echo "dependencies=$DEPENDENCIES_MAP" >> $GITHUB_OUTPUT
        shell: bash
  
  publish_package:
    needs: find_packages
    runs-on: ubuntu-latest
    environment: Dev
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.find_packages.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Configure npm registry
        run: |
              echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
              echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      
      - name: Define current package dependencies
        run: |
            DEPENDENCIES_JSON='${{ needs.find_packages.outputs.dependencies }}'
            DEPS_JSON=$(echo $DEPENDENCIES_JSON | jq -c '.["${{ matrix.package }}"]')
            echo "PACKAGE_DEPENDENCIES=$DEPS_JSON" >> $GITHUB_ENV
      
      - name: Check packages availability
        run: |
              # Convert JSON array to Bash array using jq
              readarray -t packages < <(echo "$PACKAGE_DEPENDENCIES" | jq -r '.[]')

              # Function to check package availability
              check_packages() {
                for package in "${packages[@]}"; do
                  # Use npm info to check if the package is available
                  if ! npm info "$package" > /dev/null 2>&1; then
                    echo "Package $package is not available."
                    return 1
                  fi
                done
                echo "All packages are available."
                return 0
              }

              # Loop until all packages are available
              while ! check_packages; do
                echo "Not all packages are available yet. Retrying in 15 seconds..."
                sleep 15
              done

      - name: Install dependencies for publishing
        run: ls # npm install        

      - name: Unpublish existing package version
        run: ls # npm unpublish --force
        continue-on-error: true

      - name: publish the new package version
        run: ls # npm publish
        