name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
          echo "Finding directories with package.json..."
          PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;)
          echo "Found packages: $PACKAGES"
          
          # Format the output into a JSON array of strings
          JSON_ARRAY=$(echo $PACKAGES | jq -R -s -c 'split("\n")[:-1]')
          echo "Matrix: $JSON_ARRAY"
          
          # Write the matrix to an environment file
          echo "MATRIX=${JSON_ARRAY}" >> $GITHUB_OUTPUT

      - name: Output matrix
        run: |
          MATRIX_JSON=$(echo $MATRIX | jq -c '[.[] | {package: .}]')
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

  publish:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(steps.set-matrix.outputs.matrix)}}
    environment: Dev
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies and publish package
        working-directory: ${{ matrix.package }}
        run: |
          npm install
          ls
