name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
              echo "Finding package.json files..."
              # Find all package.json files, excluding those in node_modules directories
              PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*')

              echo "Found package.json files:"
              echo "$PACKAGES"

              # Prepare an associative array to store file paths and package names
              declare -A PACKAGE_MAP

              # Loop over each found package.json file
              for PACKAGE_PATH in $PACKAGES
              do
                  # Read the 'name' attribute from package.json
                  if [ -f "$PACKAGE_PATH" ]; then
                      PACKAGE_NAME=$(jq -r '.name' "$PACKAGE_PATH")
                      # Using the full path as the key and the package name as the value
                      PACKAGE_MAP["$PACKAGE_PATH"]="$PACKAGE_NAME"
                  fi
              done

              # Output the map as a JSON object
              JSON_OBJECT=$(jq -n '$ARGS.positional | from_entries' --args -- "${PACKAGE_MAP[@]}")
              echo "Package map: $JSON_OBJECT"
        shell: bash