name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version here

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Upload node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Run tests
        run: ls

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Run lint
        run: ls

  coverage:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Run coverage
        run: ls
