name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      dependencies: ${{ steps.set-matrix.outputs.dependencies }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
              echo "Finding package.json files..."
              # Find all package.json files, excluding those in node_modules directories
              PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*')

              echo "Found package.json files:"
              echo "$PACKAGES"

              MATRIX_JSON={\"include\":$(echo "$PACKAGES" | jq -R -s -c 'split("\n")[:-1] | map({"package": (. | rtrimstr("/package.json"))})')}
              echo "matrix = $MATRIX_JSON"
              echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

        shell: bash
  
  build:
    needs: find_packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.find_packages.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Current package
        run: |
            DEPENDENCIES_JSON='${{ needs.find_packages.outputs.dependencies }}'
            # DEPS_JSON=$(echo $DEPENDENCIES_JSON | jq -c '.["${{ matrix.package }}"]')
            echo "current package: ${{ matrix.package }}" # with dependencies: $DEPS_JSON
        