name: Node.js CI

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    defaults:
      run:
        working-directory: ./CommonMessages
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
          npm install

      - name: Save node modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run tests
        run: ls

  lint:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./CommonMessages
    steps:
      - uses: actions/checkout@v2

      - name: Download node modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run linter
        run: ls
