name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
              echo "Finding directories with package.json..."
                # Find all directories containing package.json, excluding node_modules directories
                PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;)
                echo "Found packages: $PACKAGES"

                # Prepare an array to store package names
                PACKAGE_NAMES=()

                # Loop over each directory containing package.json
                for PACKAGE_DIR in $PACKAGES
                do
                    # Read the 'name' attribute from package.json
                    if [ -f "$PACKAGE_DIR/package.json" ]; then
                        PACKAGE_NAME=$(jq -r '.name' "$PACKAGE_DIR/package.json")
                        PACKAGE_NAMES+=("$PACKAGE_NAME")
                    fi
                done

                # Convert package names array to JSON array
                JSON_ARRAY=$(printf '%s\n' "${PACKAGE_NAMES[@]}" | jq -R -s -c 'split("\n")[:-1]')
                echo "Package names: $JSON_ARRAY"
        shell: bash