name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
              echo "Finding package.json files..."
              # Find all package.json files, excluding those in node_modules directories
              PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*')

              echo "Found package.json files:"
              echo "$PACKAGES"

              # Start JSON object
              JSON_OBJECT="{}"

              # Loop over each found package.json file
              for PACKAGE_PATH in $PACKAGES
              do
                  # Read the 'name' attribute from package.json
                  if [ -f "$PACKAGE_PATH" ]; then
                      PACKAGE_NAME=$(jq -r '.name' "$PACKAGE_PATH")
                      # Build JSON object by injecting each key-value pair
                      JSON_OBJECT=$(echo "$JSON_OBJECT" | jq --arg path "$PACKAGE_PATH" --arg name "$PACKAGE_NAME" '. + {($path): $name}')
                  fi
              done

              echo "Package map: $JSON_OBJECT"

        shell: bash