name: Publish Packages to Verdaccio

on:
  push:
    branches:
      - development

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - id: set-matrix
        run: |
          echo "Finding directories with package.json..."
          PACKAGES=$(find . -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;)
          echo "Found packages: $PACKAGES"
          
          JSON_ARRAY=$(echo "$PACKAGES" | jq -R -s -c 'split("\n")[:-1] | map(.)')
          echo "Matrix: $JSON_ARRAY"
          
          echo "matrix={\"include\":$(echo $JSON_ARRAY | jq -c '[.[] | {package: .}]')}" >> $GITHUB_OUTPUT
        shell: bash

  publish:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.matrix)}}
    environment: Dev
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Configure npm registry
        run: |
              echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
              echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc

      - name: Install dependencies
        run: npm install

      - name: Unpublish existing package version
        run: npm unpublish --force
        continue-on-error: true

      - name: publish the new package version
        run: npm publish
