name: Publish CommonMessages package to Verdaccio

on:
    push:
      branches:
        - development
      paths:
        - 'CommonMessages/**'
        - '.github/workflows/publish-commonmessages.yml'

jobs:
    publish-to-verdaccio:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Configure npm registry
              run: |
                # echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
                # echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
                ls
            
            - name: Unpublish existing package version
              run: echo 'unpublish' # npm unpublish --force
              continue-on-error: true

            - name: Install package dependencies
              run: echo 'install deps' # npm install

            - name: Publish CommonMessages package to Verdaccio
              run: echo 'publish to verdaccio' # npm publish
