name: Publish CommonMessages package to Verdaccio in development environment

on:
    push:
      branches:
        - development
      paths:
        - 'CommonMessages/**'
        - '.github/workflows/publish-common-messages.yml'

jobs:
    publish-to-verdaccio:
        runs-on: ubuntu-latest
        environment: Dev
        defaults:
          run:
            working-directory: './CommonMessages'
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Configure npm registry
              run: |
                echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
                echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
            
            - name: Unpublish existing package version
              run: npm unpublish --force
              continue-on-error: true

            - name: Install package dependencies
              run: npm install

            - name: Publish CommonMessages package to Verdaccio
              run: npm publish
